# Generated by Django 3.2.8 on 2021-10-15 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IndustryIdentifiers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=150, verbose_name='typ')),
                ('identifier', models.CharField(max_length=150, verbose_name='identyfikator')),
            ],
        ),
        migrations.CreateModel(
            name='ReadingModes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.BooleanField(verbose_name='tekst')),
                ('image', models.BooleanField(verbose_name='obrazek')),
            ],
        ),
        migrations.CreateModel(
            name='SaleInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=10, verbose_name='kraj')),
                ('saleability', models.CharField(choices=[('NOT_FOR_SALE', 'NOT_FOR_SALE'), ('FOR_SALE', 'FOR_SALE')], default='FOR_SALE', max_length=12)),
                ('is_ebook', models.BooleanField(verbose_name='ebook')),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='tytuł')),
                ('authors', models.CharField(max_length=450, verbose_name='autorzy')),
                ('published_date', models.DateField(verbose_name='data publikacji')),
                ('page_count', models.SmallIntegerField(verbose_name='liczba stron')),
                ('print_type', models.CharField(max_length=15, verbose_name='typ wydruku')),
                ('average_rating', models.SmallIntegerField(verbose_name='średnia ocena')),
                ('ratings_count', models.SmallIntegerField(verbose_name='liczba ocen')),
                ('language', models.CharField(max_length=5, verbose_name='język')),
                ('industry_identifiers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.industryidentifiers')),
                ('reading_modes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.readingmodes')),
                ('sale_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.saleinfo')),
            ],
        ),
    ]
