# Generated by Django 3.2.8 on 2021-10-18 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='average_rating',
            field=models.SmallIntegerField(max_length=5, verbose_name='średnia ocena'),
        ),
        migrations.AlterField(
            model_name='book',
            name='categories',
            field=models.CharField(choices=[('NONE', 'NONE'), ('HISTORY', 'HISTORY'), ('FANTASY', 'FANTASY')], default='NONE', max_length=20),
        ),
    ]
