# Generated by Django 3.2.8 on 2021-10-15 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_auto_20211015_1357'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='industry_identifiers',
        ),
        migrations.AddField(
            model_name='book',
            name='industry_identifiers',
            field=models.ManyToManyField(to='books.IndustryIdentifiers'),
        ),
    ]
