# Generated by Django 3.2.8 on 2021-10-15 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_auto_20211015_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='industry_identifiers',
            field=models.ManyToManyField(to='books.IndustryIdentifiers', verbose_name='identyfikator branżowy'),
        ),
        migrations.RemoveField(
            model_name='book',
            name='reading_modes',
        ),
        migrations.AddField(
            model_name='book',
            name='reading_modes',
            field=models.ManyToManyField(to='books.ReadingModes', verbose_name='tryb czytania'),
        ),
        migrations.RemoveField(
            model_name='book',
            name='sale_info',
        ),
        migrations.AddField(
            model_name='book',
            name='sale_info',
            field=models.ManyToManyField(to='books.SaleInfo', verbose_name='informacja o sprzedaży'),
        ),
    ]
